language: php

php:
  - 5.4
  - 5.5
#  - hhvm # commented until composer or hhvm get fixed: https://github.com/facebook/hhvm/issues/1347

install:
  - composer self-update && composer --version
  - composer install --dev --prefer-dist
  - php vendor/bin/codecept build
  - php -S localhost:3000 -t web &

before_script:
  - mysql -e 'CREATE DATABASE konani_acceptance;';
  - mysql -e 'CREATE DATABASE konani_functional;';
  - mysql -e 'CREATE DATABASE konani_unit;';

script:
  - php vendor/bin/codecept run

#after_script:
#  - php vendor/bin/coveralls
