language: php

php:
  - 5.4
  - 5.5
#  - hhvm # commented until composer or hhvm get fixed: https://github.com/facebook/hhvm/issues/1347

#services:
#  - memcached

install:
  - composer self-update && composer --version
  - composer install --prefer-dist
  - tests/unit/data/travis/memcache-setup.sh
  - php vendor/bin/codecept build
  - php -S localhost:3000 -t web &

before_script:
  - mysql -e 'CREATE DATABASE yiitest;';

script:
  - cd apps/basic && php vendor/bin/codecept run

#after_script:
#  - php vendor/bin/coveralls
